export const listCity = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Đăk Lăk",
  "Đăk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Tĩnh",
  "Hải Dương",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Nình Thuận",
  "Phú Thọ",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yến Bái",
  "Phú Yên",
  "Cần Thơ",
  "Đà Nẵng",
  "Hải Phòng",
  "Hà Nội",
  "TP Hồ Chí Minh",
];

export const hostpitalList = [
  "Bệnh viện Bạch Mai",
  "Bệnh viện Hữu Nghị",
  "Bệnh viện E, Hà Nội",
  "Bệnh Viện Răng Hàm Mặt Trung Ương Hà Nội",
  "Bệnh viện tai mũi họng Trung Ương Hà Nội",
  "Bệnh viện mắt Trung Ương Hà Nội ",
  "Bệnh Viện y học cổ truyền  Trung Ương Hà Nội",
  "Bệnh viện nội tiết Trung Ương Hà Nội",
  "Bệnh viện K",
  "Bệnh viện Việt Đức",
  "BỆNH VIỆN MẮT SÀI GÒN",
  "BỆNH VIỆN MẮT SÀI GÒN",
];
