export const dataSource = [
  {
    key: "1",
    name: "Mau01",
    hospital: "TTYT huyện Hiệp Đức",
    manager: "Nguyễn Đinh Mậu",
    address: "10 Downing Street",
    role: "owner",
  },
  {
    key: "2",
    name: "Mau02",
    hospital: "BV NHI ĐỒNG THÀNH PHỐ CẦN THƠ",
    manager: "Nguyễn Đinh Mậu",
    address: "10 Downing Street",
    role: "owner",
  },
  {
    key: "3",
    name: "Mau03",
    hospital: "TTYT huyện Hiệp Đức",
    manager: "Nguyễn Đinh Mậu",
    address: "10 Downing Street",
    role: "owner",
  },
  {
    key: "4",
    name: "Mau04",
    hospital: "BV NHI ĐỒNG THÀNH PHỐ CẦN THƠ",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "5",
    name: "Mau05",
    hospital: "TTYT huyện Hiệp Đức",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "6",
    name: "Mau06",
    hospital: "BV NHI ĐỒNG THÀNH PHỐ CẦN THƠ",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "7",
    name: "Mau07",
    hospital: "TTYT huyện Hiệp Đức",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "8",
    name: "Mau08",
    hospital: "BV NHI ĐỒNG THÀNH PHỐ CẦN THƠ",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "9",
    name: "Mau09",
    hospital: "TTYT huyện Hiệp Đức",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "10",
    name: "Mau10",
    hospital: "BV NHI ĐỒNG THÀNH PHỐ CẦN THƠ",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "11",
    name: "Mau11",
    hospital: "TTYT huyện Hiệp Đức",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
  {
    key: "12",
    name: "Mau12",
    hospital: "BV NHI ĐỒNG THÀNH PHỐ CẦN THƠ",
    manager: "Nguyễn Đinh Mậu",
    role: "owner",
    address: "10 Downing Street",
  },
];
